//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiitBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public Albums()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public string Description { get; set; }
        public string CoverPath { get; set; }
        public Nullable<int> PhotoNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int UID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
