//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiitBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.ArticleTagMapping = new HashSet<ArticleTagMapping>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int AID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> ViewNum { get; set; }
        public Nullable<int> CommentNum { get; set; }
        public int CID { get; set; }
        public int UID { get; set; }
        public string Summery { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ArticleTagMapping> ArticleTagMapping { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
