//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiitBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTagMapping
    {
        public int AID { get; set; }
        public int TID { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
