//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiitBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public Photos()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int PID { get; set; }
        public string PhotoName { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int AlbumID { get; set; }
        public int UID { get; set; }
        public string Thumbnailw { get; set; }
        public Nullable<int> Thumbnailw_width { get; set; }
        public Nullable<int> Thumbnailw_height { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Users Users { get; set; }
    }
}
